sudo: required

language: c

os: linux

dist: trusty

compiler: arm-none-eabi-gcc

before_install:
  - sudo add-apt-repository -y ppa:team-gcc-arm-embedded/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded

install:
  - wget https://github.com/stateos/StateOS/archive/master.zip
  - unzip -q master.zip
  - mv -T StateOS-master/StateOS/kernel/ StateOS/kernel/
  - mv -T StateOS-master/StateOS/port/CORTEXM/ StateOS/port/CORTEXM/
  - rm -r StateOS-master

before_script: arm-none-eabi-gcc --version

script: make all GNUCC=arm-none-eabi- -f makefile.gnucc

group: stable
